version: '3.4'

services:
  micromarincase.api:
    image: ${DOCKER_REGISTRY-}micromarincaseapi
    build:
      context: .
      dockerfile: src/MicroMarinCase.Api/Dockerfile
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false  # Globalization Invariant modunu kapatır
    networks:
      - db-network
    depends_on:
      - micromarin.mssql

  micromarin.mssql:
    container_name: micromarin-sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1234qwer."
    ports:
      - 1400:1433
    volumes:
      - my-volume:/var/opt/mssql
    networks:
      - db-network

volumes:
  my-volume:

networks:
  db-network:
    driver: bridge